const FOGALOM = [

    "BECSÜLET",
    "REMÉNY",
    "HONVÁGY",
    "SZERETET",
    "BIZALOM",
    "BARÁTSÁG",
    "HŰSÉG",
    "BÁTORSÁG",
    "TÜRELEM",
    "BÜSZKESÉG",

    "ÖRÖM",
    "BÁNAT",
    "FÉLELEM",
    "HARAG",
    "NYUGALOM",
    "BÉKESSÉG",
    "SZABADSÁG",
    "IGAZSÁG",
    "JÓSÁG",
    "HÁLA",

    "IRIGYSÉG",
    "FÉLTÉKENYSÉG",
    "KÍVÁNCSISÁG",
    "EGYÜTTÉRZÉS",
    "MEGBOCSÁTÁS",
    "TISZTELET",
    "ŐSZINTESÉG",
    "HŰTLENSÉG",
    "SZORGALOM",
    "KITARTÁS",

    "AKARATERŐ",
    "ÖNBIZALOM",
    "ÖNBECSÜLÉS",
    "ALÁZAT",
    "KEGYESSÉG",
    "NAGYLELKŰSÉG",
    "SEGÍTŐKÉSZSÉG",
    "UDVARIASSÁG",
    "FELELŐSSÉG",
    "KÖTELESSÉG",

    "LELKIISMERET",
    "BŰNTUDAT",
    "MEGBÁNÁS",
    "CSALÓDOTTSÁG",
    "ELÉGEDETTSÉG",
    "ELÉGEDETLENSÉG",
    "MAGÁNY",
    "KÖZÖSSÉG",
    "ÖSSZETARTÁS",
    "CSALÁDIASSÁG",

    "ROMANTIKA",
    "SZENVEDÉLY",
    "VÁGYAKOZÁS",
    "RAJONGÁS",
    "GYENGÉDSÉG",
    "GONDOSKODÁS",
    "RAGASZKODÁS",
    "BIZTONSÁG",
    "BIZONYTALANSÁG",
    "KÉTSÉG",

    "REMÉNYTELENSÉG",
    "OPTIMIZMUS",
    "PESSZIMIZMUS",
    "VIDÁMSÁG",
    "SZOMORÚSÁG",
    "LELKESEDÉS",
    "UNALOM",
    "MEGLEPETÉS",
    "CSODÁLAT",
    "TISZTESSÉG",

    "BECSÜLETESSÉG",
    "IGAZSÁGOSSÁG",
    "HIT",
    "HŰSÉGESSÉG",
    "ÖNFEGYELEM",
    "ELSZÁNTSÁG",
    "ELHIVATOTTSÁG",
    "ÁLDOZATKÉSZSÉG",
    "BÖLCSESSÉG",
    "TAPASZTALAT",

    "EMLÉKEZÉS",
    "FELEDÉS",
    "KÉPZELET",
    "ÁLOM",
    "VÁRAKOZÁS",
    "HIÁNYÉRZET",
    "MEGKÖNNYEBBÜLÉS",
    "FESZÜLTSÉG",
    "CSALÓDÁS",
    "BOLDOGSÁG",

    "SZERÉNYSÉG",
    "TOLERANCIA",
    "HUMOR",
    "DERŰ",
    "EGYENSÚLY",
    "HARMÓNIA",
    "KÖLCSÖNÖSSÉG",
    "ELFOGADÁS",
    "MEGÉRTÉS",
    "ÖSSZHANG"

];

module.exports = FOGALOM;
