const ALLAT = [

    "OROSZLÁN",
    "TIGRIS",
    "LEOPÁRD",
    "JAGUÁR",
    "GEPÁRD",
    "HIÉNA",
    "FARKAS",
    "RÓKA",
    "ARANYSAKÁL",
    "JEGESMEDVE",

    "BARNAMEDVE",
    "ÓRIÁSPANDA",
    "VÖRÖS PANDA",
    "ELEFÁNT",
    "ORRSZARVÚ",
    "VÍZILÓ",
    "ZEBRA",
    "ZSIRÁF",
    "TEVE",
    "DROMEDÁR",

    "LÓ",
    "SZAMÁR",
    "ÖSZVÉR",
    "SZARVASMARHA",
    "BIVALY",
    "JUH",
    "KECSKE",
    "SERTÉS",
    "HÁZINYÚL",
    "HÁZIMACSKA",

    "HÁZIKUTYA",
    "HÖRCSÖG",
    "TENGERIMALAC",
    "CSINCSILLA",
    "VADNYÚL",
    "MEZEI NYÚL",
    "MÓKUS",
    "HÓD",
    "VIDRA",
    "BORZ",

    "VADDISZNÓ",
    "GÍMSZARVAS",
    "DÁMSZARVAS",
    "ŐZ",
    "JÁVORSZARVAS",
    "RÉNSZARVAS",
    "ANTILOP",
    "GAZELLA",
    "GNÚ",
    "BÖLÉNY",

    "GORILLA",
    "CSIMPÁNZ",
    "ORANGUTÁN",
    "PÁVIÁN",
    "MAKÁKÓ",
    "LEMÚR",
    "LAJHÁR",
    "HANGYÁSZ",
    "TATU",
    "KENGURU",

    "KOALA",
    "VOMBAT",
    "KACSACSŐRŰ EMLŐS",
    "TASMÁN ÖRDÖG",
    "DENEVÉR",
    "SÜN",
    "VAKOND",
    "CICKÁNY",
    "EGÉR",
    "PATKÁNY",

    "DELFIN",
    "KARDSZÁRNYÚ DELFIN",
    "ÁMBRÁSCET",
    "KÉK BÁLNA",
    "PÚPOS BÁLNA",
    "FÓKA",
    "ROZMÁR",
    "OROSZLÁNFÓKA",
    "LAMANTIN",
    "NARVÁL",

    "SAS",
    "SÓLYOM",
    "HÉJA",
    "BAGOLY",
    "HOLLÓ",
    "VARJÚ",
    "SZARKA",
    "GALAMB",
    "VEREB",
    "FECSKE",

    "GÓLYA",
    "DARU",
    "GÉM",
    "HATTYÚ",
    "VADKACSA",
    "PINGVIN",
    "STRUCC",
    "PÁVA",
    "PAPAGÁJ",
    "KOLIBRI",
	    "FLAMINGÓ",
    "PELIKÁN",
    "KORMORÁN",
    "ALBATROSZ",
    "SIRÁLY",
    "JÉGMADÁR",
    "HARKÁLY",
    "FÜLEMÜLE",
    "RIGÓ",
    "VÖRÖSBEGY",

    "CINEGE",
    "PACSIRTA",
    "FÁCÁN",
    "FOGOLY",
    "FÜRJ",
    "VADPULYKA",
    "KAKUKK",
    "BÚBOS BANKA",
    "TUKÁN",
    "KIVI",

    "KROKODIL",
    "ALIGÁTOR",
    "KAJMÁN",
    "KOMODÓI VARÁNUSZ",
    "LEGUÁN",
    "KAMÉLEON",
    "GEKKÓ",
    "ZÖLD GYÍK",
    "LÁBATLAN GYÍK",
    "MOCSÁRI TEKNŐS",

    "ÓRIÁSTEKNŐS",
    "TENGERI TEKNŐS",
    "KOBRA",
    "KIRÁLYKOBRA",
    "PITON",
    "BOA",
    "ANAKONDA",
    "CSÖRGŐKÍGYÓ",
    "VIPERA",
    "MAMBA",

    "BÉKA",
    "VARANGY",
    "LEVELIBÉKA",
    "NYÍLMÉREGBÉKA",
    "GŐTE",
    "SZALAMANDRA",
    "AXOLOTL",
    "CÁPA",
    "FEHÉR CÁPA",
    "TIGRISCÁPA",

    "PÖRÖLYCÁPA",
    "CETCÁPA",
    "RÁJA",
    "MANTA",
    "ANGOLNA",
    "MURÉNA",
    "HARCSA",
    "PONTY",
    "CSUKA",
    "SÜLLŐ",

    "PISZTRÁNG",
    "LAZAC",
    "TONHAL",
    "SZARDÍNIA",
    "HERING",
    "MAKRÉLA",
    "KARDHAL",
    "CSIKÓHAL",
    "BOHÓCHAL",
    "GÖMBHAL",

    "POLIP",
    "TINTAHAL",
    "KALMÁR",
    "NAUTILUSZ",
    "MEDÚZA",
    "TENGERI CSILLAG",
    "TENGERI SÜN",
    "TENGERI UBORKA",
    "HOMÁR",
    "LANGUSZTA",

    "RÁK",
    "GARNÉLARÁK",
    "REMETERÁK",
    "OSZTRIGA",
    "KAGYLÓ",
    "CSIGA",
    "MEZTELENCSIGA",
    "FÖLDIGILISZTA",
    "PÓK",
    "SKORPIÓ",

    "HANGYA",
    "MÉH",
    "DARÁZS",
    "POSZMÉH",
    "LEPKE",
    "MOLYLEPKE",
    "KATICABOGÁR",
    "SZARVASBOGÁR",
    "SZENTJÁNOSBOGÁR",
    "SZITAKÖTŐ",
	    "SZÖCSKE",
    "SÁSKA",
    "TÜCSÖK",
    "CSÓTÁNY",
    "IMÁDKOZÓ SÁSKA",
    "BOTROVAR",
    "LEVÉLTETŰ",
    "BOLHA",
    "TETŰ",

    "KULLANCS",
    "ATKA",
    "SZÚNYOG",
    "HÁZILÉGY",
    "BÖGÖLY",
    "MUSLICA",
    "CSEREBOGÁR",
    "GANÉJTÚRÓ BOGÁR",
    "ORMÁNYOSBOGÁR",
    "KRUMPLIBOGÁR",

    "LÁMA",
    "ALPAKA",
    "JAK",
    "PÉZSMATULOK",
    "OKAPI",
    "TAPÍR",
    "VARACSKOS DISZNÓ",
    "PEKARI",
    "MANGUSZTA",
    "SZURIKÁTA",

    "MOSÓMEDVE",
    "ORMÁNYOSMEDVE",
    "BINTURONG",
    "CIBETMACSKA",
    "NYEST",
    "NYUSZT",
    "GÖRÉNY",
    "MENYÉT",
    "HERMELIN",
    "PRÉRIFARKAS",

    "SIVATAGI RÓKA",
    "VÖRÖS RÓKA",
    "PUMA",
    "HIÚZ",
    "KARAKÁL",
    "OCELOT",
    "SZERVÁL",
    "HÓPÁRDUC",
    "KÖDFOLTOS PÁRDUC",
    "FEKETEPÁRDUC",

    "MANDRILL",
    "GIBBON",
    "BŐGŐMAJOM",
    "PÓKMAJOM",
    "KAPUCINUSMAJOM",
    "MÓKUSMAJOM",
    "TAMARIN",
    "SELYEMMAJOM",
    "PÁPASZEMES MEDVE",
    "FÖLDIMALAC",

    "TARLÓSÜN",
    "PRÉRIKUTYA",
    "ÜRGE",
    "MORMOTA",
    "PELE",
    "KÉRÉSZ",
    "AGUTI",
    "KAPIBARA",
    "DIKDIK",
    "IMPALA",

    "KUDU",
    "ELAND",
    "ZERGE",
    "KŐSZÁLI KECSKE",
    "PÉZSMASZARVAS",
    "VÍZI BIVALY",
    "VADJAK",
    "VADLÓ",
    "VADSZAMÁR",
    "MUFLON",

    "KONDOR",
    "KESELYŰ",
    "RÉTISAS",
    "KERECSENSÓLYOM",
    "VÁNDORSÓLYOM",
    "UHU",
    "GYÖNGYBAGOLY",
    "FÜLESBAGOLY",
    "HÓBAGOLY",
    "KUVIK",

    "PULYKA",
    "GYÖNGYTYÚK",
    "HÁZITYÚK",
    "HÁZILÚD",
    "HÁZIKACSA",
    "MANDARINRÉCE",
    "KANALASGÉM",
    "MARABU",
    "ÍBISZ",
    "PAPUCSCSŐRŰ MADÁR",
    "HÓDPATKÁNY",
];

module.exports = ALLAT;