const FOGLALKOZAS = [

    "TŰZOLTÓ",
    "VILLANYSZERELŐ",
    "GYÓGYSZERÉSZ",
    "ÜGYVÉD",
    "ÁPOLÓ",
    "PROGRAMOZÓ",
    "MOZDONYVEZETŐ",
    "SZAKÁCS",
    "KÖNYVELŐ",
    "ÚJSÁGÍRÓ",

    "ORVOS",
    "FOGORVOS",
    "MENTŐÁPOLÓ",
    "VÉDŐNŐ",
    "GYÓGYTORNÁSZ",
    "PSZICHOLÓGUS",
    "DIETETIKUS",
    "LABORÁNS",
    "RADIOLÓGIAI ASSZISZTENS",
    "MŰTŐSSEGÉD",

    "TANÁR",
    "TANÍTÓ",
    "ÓVODAPEDAGÓGUS",
    "GYÓGYPEDAGÓGUS",
    "ISKOLATITKÁR",
    "KÖNYVTÁROS",
    "OKTATÁSSZERVEZŐ",
    "EGYETEMI OKTATÓ",
    "KOLLÉGIUMI NEVELŐ",
    "PEDAGÓGIAI ASSZISZTENS",

    "RENDŐR",
    "KATONA",
    "BIZTONSÁGI ŐR",
    "BÖRTÖNŐR",
    "VÁMÜGYINTÉZŐ",
    "NYOMOZÓ",
    "HELYSZÍNELŐ",
    "KÖRZETI MEGBÍZOTT",
    "KATASZTRÓFAVÉDELMI ÜGYINTÉZŐ",
    "POLGÁRŐR",

    "PINCÉR",
    "CUKRÁSZ",
    "PÉK",
    "HENTES",
    "BARISTA",
    "BÁRTENDER",
    "KONYHAI KISEGÍTŐ",
    "ÉTTEREMVEZETŐ",
    "SZÁLLODAI RECEPCIÓS",
    "SZOBALÁNY",

    "KŐMŰVES",
    "ÁCS",
    "BURKOLÓ",
    "FESTŐ-MÁZOLÓ",
    "VÍZVEZETÉK-SZERELŐ",
    "GÁZSZERELŐ",
    "HEGESZTŐ",
    "LAKATOS",
    "ESZTERGÁLYOS",
    "ASZTALOS",

    "AUTÓSZERELŐ",
    "AUTÓVILLAMOSSÁGI SZERELŐ",
    "KAROSSZÉRIALAKATOS",
    "GUMISZERELŐ",
    "MŰSZAKI VIZSGABIZTOS",
    "TARGONCAVEZETŐ",
    "TEHERAUTÓ-SOFŐR",
    "BUSZSOFŐR",
    "TAXISOFŐR",
    "FUTÁR",

    "POSTÁS",
    "RAKTÁROS",
    "LOGISZTIKAI ÜGYINTÉZŐ",
    "BESZERZŐ",
    "PÉNZTÁROS",
    "ELADÓ",
    "BOLTVEZETŐ",
    "PIACI ÁRUS",
    "ÜGYFÉLSZOLGÁLATI MUNKATÁRS",
    "TELEFONOS ÜGYINTÉZŐ",

    "BANKI ÜGYINTÉZŐ",
    "PÉNZÜGYI TANÁCSADÓ",
    "BIZTOSÍTÁSI ÜGYINTÉZŐ",
    "KÖNYVVIZSGÁLÓ",
    "BÉRSZÁMFEJTŐ",
    "ADÓTANÁCSADÓ",
    "GAZDASÁGI ÜGYINTÉZŐ",
    "IRODAVEZETŐ",
    "RECEPCIÓS",
    "TITKÁRNŐ",

    "FODRÁSZ",
    "KOZMETIKUS",
    "SMINKES",
    "MŰKÖRMÖS",
    "MASSZŐR",
    "FÉNYKÉPÉSZ",
    "VIDEÓS",
    "GRAFIKUS",
    "DEKORATŐR",
    "VARRÓNŐ",
	    "KOVÁCS",
    "BÁDOGOS",
    "TETŐFEDŐ",
    "ÜVEGES",
    "KÉMÉNYSEPRŐ",
    "PARKETTÁZÓ",
    "SZIGETELŐ",
    "ÉPÍTÉSZ",
    "ÉPÍTÉSZTECHNIKUS",
    "ÉPÍTÉSVEZETŐ",

    "KERTÉSZ",
    "KERTÉPÍTŐ",
    "ERDÉSZ",
    "VADÁSZ",
    "HALÁSZ",
    "MÉHÉSZ",
    "ÁLLATORVOS",
    "ÁLLATGONDOZÓ",
    "KUTYAKOZMETIKUS",
    "LÓGONDOZÓ",

    "GAZDA",
    "MEZŐGAZDASÁGI GÉPKEZELŐ",
    "TRAKTORVEZETŐ",
    "NÖVÉNYTERMESZTŐ",
    "ÁLLATTENYÉSZTŐ",
    "BORÁSZ",
    "SZŐLÉSZ",
    "TEJIPARI MUNKÁS",
    "MOLNÁR",
    "SAJTKÉSZÍTŐ",

    "GÉPÉSZMÉRNÖK",
    "VILLAMOSMÉRNÖK",
    "ÉPÍTŐMÉRNÖK",
    "VEGYÉSZMÉRNÖK",
    "KÖRNYEZETMÉRNÖK",
    "INFORMATIKUS",
    "RENDSZERGAZDA",
    "SZOFTVERFEJLESZTŐ",
    "WEBFEJLESZTŐ",
    "HÁLÓZATI RENDSZERÜZEMELTETŐ",

    "ADATBÁZIS-KEZELŐ",
    "SZOFTVERTESZTELŐ",
    "RENDSZERELEMZŐ",
    "INFORMATIKAI TECHNIKUS",
    "SZERVIZTECHNIKUS",
    "ELEKTRONIKAI MŰSZERÉSZ",
    "MECHATRONIKAI TECHNIKUS",
    "GÉPSZERELŐ",
    "GÉPKEZELŐ",
    "DARUKEZELŐ",

    "SZÍNÉSZ",
    "SZINKRONSZÍNÉSZ",
    "RENDEZŐ",
    "FORGATÓKÖNYVÍRÓ",
    "OPERATŐR",
    "VÁGÓ",
    "HANGMÉRNÖK",
    "ZENÉSZ",
    "ÉNEKES",
    "KARMESTER",

    "ZONGORISTA",
    "HEGEDŰMŰVÉSZ",
    "TÁNCOS",
    "KOREOGRÁFUS",
    "BÁBSZÍNÉSZ",
    "CIRKUSZMŰVÉSZ",
    "BŰVÉSZ",
    "MŰSORVEZETŐ",
    "RÁDIÓS MŰSORVEZETŐ",
    "TELEVÍZIÓS SZERKESZTŐ",

    "ÍRÓ",
    "KÖLTŐ",
    "SZERKESZTŐ",
    "KORREKTOR",
    "FORDÍTÓ",
    "TOLMÁCS",
    "LEVÉLTÁROS",
    "MUZEOLÓGUS",
    "RÉGÉSZ",
    "TÖRTÉNÉSZ",

    "BIOLÓGUS",
    "VEGYÉSZ",
    "FIZIKUS",
    "CSILLAGÁSZ",
    "METEOROLÓGUS",
    "GEOLÓGUS",
    "KUTATÓ",
    "MATEMATIKUS",
    "STATISZTIKUS",
    "TÉRKÉPÉSZ",

    "LÉGIUTAS-KÍSÉRŐ",
    "PILÓTA",
    "LÉGIFORGALMI IRÁNYÍTÓ",
    "HAJÓKAPITÁNY",
    "HAJÓGÉPÉSZ",
    "VILLAMOSVEZETŐ",
    "METRÓVEZETŐ",
    "FORGALMISTA",
    "JEGYVIZSGÁLÓ",
    "DISZPÉCSER",
	    "SZOCIÁLIS MUNKÁS",
    "SZOCIÁLIS GONDOZÓ",
    "IDŐSGONDOZÓ",
    "HÁZI GONDOZÓ",
    "GYERMEKFELÜGYELŐ",
    "BÖLCSŐDEI KISGYERMEKNEVELŐ",
    "CSALÁDSEGÍTŐ",
    "MENTÁLHIGIÉNÉS SZAKEMBER",
    "JELNYELVI TOLMÁCS",
    "SZEMÉLYI SEGÍTŐ",

    "EDZŐ",
    "SZEMÉLYI EDZŐ",
    "ÚSZÓEDZŐ",
    "FUTBALLEDZŐ",
    "SPORTBÍRÓ",
    "JÁTÉKVEZETŐ",
    "ÚSZÓMESTER",
    "SPORTSZERVEZŐ",
    "FITNESZOKTATÓ",
    "JÓGAOKTATÓ",

    "IDEGENVEZETŐ",
    "UTAZÁSI ÜGYINTÉZŐ",
    "TÚRAVEZETŐ",
    "RENDEZVÉNYSZERVEZŐ",
    "RENDEZVÉNYTECHNIKUS",
    "PORTÁS",
    "GONDNOK",
    "TAKARÍTÓ",
    "ABLAKTISZTÍTÓ",
    "KÁRTEVŐIRTÓ",

    "KUKÁS",
    "UTCASEPRŐ",
    "PARKGONDOZÓ",
    "TEMETŐGONDNOK",
    "SÍRÁSÓ",
    "KERTÉSZETI MUNKÁS",
    "ERDŐMŰVELŐ",
    "FAKITERMELŐ",
    "FAVÁGÓ",
    "KOSÁRFONÓ",

    "FAZEKAS",
    "KÁDÁR",
    "TAKÁCS",
    "SZŰCS",
    "CIPÉSZ",
    "KALAPOS",
    "ÓRÁS",
    "ÖTVÖS",
    "ÉKSZERÉSZ",
    "KŐFARAGÓ",

    "HARANGÖNTŐ",
    "KÖNYVKÖTŐ",
    "NYOMDÁSZ",
    "BETŰSZEDŐ",
    "KÁRPITOS",
    "MŰBÚTORASZTALOS",
    "PORCELÁNFESTŐ",
    "KERAMIKUS",
    "ÜVEGMŰVES",
    "SZOBRÁSZ",

    "FESTŐMŰVÉSZ",
    "ILLUSZTRÁTOR",
    "DIVATTERVEZŐ",
    "LAKBERENDEZŐ",
    "BELSŐÉPÍTÉSZ",
    "DÍSZLETTERVEZŐ",
    "JELMEZTERVEZŐ",
    "HANGSZERKÉSZÍTŐ",
    "VIRÁGKÖTŐ",
    "TETOVÁLÓ",

    "BÍRÓ",
    "ÜGYÉSZ",
    "KÖZJEGYZŐ",
    "JOGTANÁCSOS",
    "BÍRÓSÁGI TITKÁR",
    "VÉGREHAJTÓ",
    "KÖZIGAZGATÁSI ÜGYINTÉZŐ",
    "ANYAKÖNYVVEZETŐ",
    "HIVATALI ÜGYINTÉZŐ",
    "IRATTÁROS",

    "MARKETINGES",
    "REKLÁMSZAKEMBER",
    "SAJTÓREFERENS",
    "PR-MENEDZSER",
    "ÉRTÉKESÍTŐ",
    "INGATLANKÖZVETÍTŐ",
    "HR-MUNKATÁRS",
    "TOBORZÓ",
    "PROJEKTMENEDZSER",
    "TERMÉKMENEDZSER",

    "MOSOGATÓ",
    "PIZZASZAKÁCS",
    "HIDEGKONYHAI SZAKÁCS",
    "HÁZVEZETŐNŐ",
    "BÉBISZITTER",
    "KUTYASÉTÁLTATÓ",
    "AUTÓMOSÓ",
    "BENZINKUTAS",
    "PARKOLÓŐR",
    "KULCSMÁSOLÓ"

];

module.exports = FOGLALKOZAS;