const FOLDRAJZ = [

    "MAGYARORSZÁG",
    "AUSZTRIA",
    "NÉMETORSZÁG",
    "FRANCIAORSZÁG",
    "OLASZORSZÁG",
    "SPANYOLORSZÁG",
    "PORTUGÁLIA",
    "SVÁJC",
    "BELGIUM",
    "HOLLANDIA",

    "LENGYELORSZÁG",
    "CSEHORSZÁG",
    "SZLOVÁKIA",
    "SZLOVÉNIA",
    "HORVÁTORSZÁG",
    "SZERBIA",
    "ROMÁNIA",
    "BULGÁRIA",
    "GÖRÖGORSZÁG",
    "ALBÁNIA",

    "NORVÉGIA",
    "SVÉDORSZÁG",
    "FINNORSZÁG",
    "DÁNIA",
    "IZLAND",
    "ÍRORSZÁG",
    "EGYESÜLT KIRÁLYSÁG",
    "ÉSZTORSZÁG",
    "LETTORSZÁG",
    "LITVÁNIA",

    "UKRAJNA",
    "MOLDOVA",
    "TÖRÖKORSZÁG",
    "GRÚZIA",
    "ÖRMÉNYORSZÁG",
    "CIPRUS",
    "MÁLTA",
    "LUXEMBURG",
    "MONACO",
    "LIECHTENSTEIN",

    "BUDAPEST",
    "BÉCS",
    "BERLIN",
    "PÁRIZS",
    "RÓMA",
    "MADRID",
    "LISSZABON",
    "PRÁGA",
    "POZSONY",
    "VARSÓ",

    "BUKAREST",
    "SZÓFIA",
    "ATHÉN",
    "BELGRÁD",
    "ZÁGRÁB",
    "LJUBLJANA",
    "OSLO",
    "STOCKHOLM",
    "HELSINKI",
    "KOPPENHÁGA",

    "REYKJAVÍK",
    "DUBLIN",
    "LONDON",
    "TALLINN",
    "RIGA",
    "VILNIUS",
    "KIJEV",
    "ANKARA",
    "BRÜSSZEL",
    "AMSZTERDAM",

    "DUNA",
    "TISZA",
    "DRÁVA",
    "SZÁVA",
    "RAJNA",
    "ELBA",
    "TEMZE",
    "SZENT LŐRINC-FOLYÓ",
    "MISSISSIPPI",
    "AMAZONAS",

    "NÍLUS",
    "KONGÓ",
    "GANGESZ",
    "JANGCE",
    "SÁRGA-FOLYÓ",
    "MEKONG",
    "VOLGA",
    "DONYEC",
    "EUFRÁTESZ",
    "COLORADO-FOLYÓ",

    "ALPOK",
    "KÁRPÁTOK",
    "PIRINEUSOK",
    "APPENNINEK",
    "HIMALÁJA",
    "ANDOK",
    "SZIKLÁS-HEGYSÉG",
    "URÁL",
    "KAUKÁZUS",
    "ATLASZ",
	    "EGYESÜLT ÁLLAMOK",
    "KANADA",
    "MEXIKÓ",
    "BRAZÍLIA",
    "ARGENTÍNA",
    "CHILE",
    "PERU",
    "BOLÍVIA",
    "KOLUMBIA",
    "VENEZUELA",

    "URUGUAY",
    "PARAGUAY",
    "ECUADOR",
    "KUBA",
    "JAMAICA",
    "PANAMA",
    "COSTA RICA",
    "GUATEMALA",
    "DOMINIKAI KÖZTÁRSASÁG",
    "BAHAMÁK",

    "EGYIPTOM",
    "MAROKKÓ",
    "ALGÉRIA",
    "TUNÉZIA",
    "LÍBIA",
    "ETIÓPIA",
    "KENYA",
    "TANZÁNIA",
    "DÉL-AFRIKAI KÖZTÁRSASÁG",
    "MADAGASZKÁR",

    "NIGÉRIA",
    "GHÁNA",
    "SZENEGÁL",
    "NAMÍBIA",
    "BOTSWANA",
    "ZIMBABWE",
    "ZAMBIA",
    "MOZAMBIK",
    "ANGOLA",
    "KAMERUN",

    "KÍNA",
    "JAPÁN",
    "INDIA",
    "PAKISZTÁN",
    "BANGLADES",
    "NEPÁL",
    "BHUTÁN",
    "MONGÓLIA",
    "DÉL-KOREA",
    "ÉSZAK-KOREA",

    "THAIFÖLD",
    "VIETNÁM",
    "KAMBODZSA",
    "LAOSZ",
    "MALAJZIA",
    "SZINGAPÚR",
    "INDONÉZIA",
    "FÜLÖP-SZIGETEK",
    "SRÍ LANKA",
    "MALDÍV-SZIGETEK",

    "AUSZTRÁLIA",
    "ÚJ-ZÉLAND",
    "PÁPUA ÚJ-GUINEA",
    "FIDZSI",
    "SZAMOA",
    "WASHINGTON",
    "OTTAWA",
    "MEXIKÓVÁROS",
    "BRASÍLIA",
    "BUENOS AIRES",

    "TOKIÓ",
    "PEKING",
    "ÚJDELHI",
    "SZÖUL",
    "BANGKOK",
    "HANOI",
    "KAIRO",
    "RABAT",
    "NAIROBI",
    "CANBERRA",

    "CSENDES-ÓCEÁN",
    "ATLANTI-ÓCEÁN",
    "INDIAI-ÓCEÁN",
    "ÉSZAKI-JEGES-TENGER",
    "FÖLDKÖZI-TENGER",
    "FEKETE-TENGER",
    "VÖRÖS-TENGER",
    "ADRIAI-TENGER",
    "BALTI-TENGER",
    "ÉSZAKI-TENGER",

    "KASZPI-TENGER",
    "HOLT-TENGER",
    "BAJKÁL-TÓ",
    "VIKTÓRIA-TÓ",
    "TANGANYIKA-TÓ",
    "TITICACA-TÓ",
    "NAGY-KORALLZÁTONY",
    "SZAHARA",
    "GÓBI-SIVATAG",
    "KALAHÁRI-SIVATAG",
	    "MOUNT EVEREST",
    "KILIMANDZSÁRÓ",
    "MONT BLANC",
    "MATTERHORN",
    "OLÜMPOSZ",
    "ETNA",
    "VEZÚV",
    "FUJI",
    "KRAKATAU",
    "MAUNA LOA",

    "NIAGARA-VÍZESÉS",
    "VIKTÓRIA-VÍZESÉS",
    "ANGYAL-VÍZESÉS",
    "IGUAZÚ-VÍZESÉS",
    "RAJNA-VÍZESÉS",
    "GRAND CANYON",
    "COLORADO-FENNSÍK",
    "TIBETI-FENNSÍK",
    "PAMÍR",
    "SZIBÉRIA",

    "GRÖNLAND",
    "IZLANDI-FENNSÍK",
    "CEYLON",
    "BORNEÓ",
    "SZUMÁTRA",
    "JÁVA",
    "SZULAVÉZI",
    "ÚJ-GUINEA",
    "TAJVAN",
    "SZICÍLIA",

    "SZARDÍNIA",
    "KORZIKA",
    "KRÉTA",
    "RODOSZ",
    "MÁLTAI-SZIGETEK",
    "KANÁRI-SZIGETEK",
    "BALEÁR-SZIGETEK",
    "HAWAII-SZIGETEK",
    "GALÁPAGOS-SZIGETEK",
    "HÚSVÉT-SZIGET",

    "ARAB-FÉLSZIGET",
    "IBÉRIAI-FÉLSZIGET",
    "BALKÁN-FÉLSZIGET",
    "SKANDINÁV-FÉLSZIGET",
    "APPENNINI-FÉLSZIGET",
    "KAMCSATKA-FÉLSZIGET",
    "KOREAI-FÉLSZIGET",
    "INDOKÍNAI-FÉLSZIGET",
    "JUKATÁN-FÉLSZIGET",
    "FLORIDA-FÉLSZIGET",

    "GIBRALTÁRI-SZOROS",
    "BERING-SZOROS",
    "BOSZPORUSZ",
    "DARDANELLÁK",
    "LA MANCHE",
    "MAGELLÁN-SZOROS",
    "PANAMA-CSATORNA",
    "SZUEZI-CSATORNA",
    "KIELI-CSATORNA",
    "KORINTHOSZI-CSATORNA",

    "MEXIKÓI-ÖBÖL",
    "PERZSA-ÖBÖL",
    "BENGÁLI-ÖBÖL",
    "HUDSON-ÖBÖL",
    "GUINEAI-ÖBÖL",
    "BISZKAJAI-ÖBÖL",
    "BOTNIAI-ÖBÖL",
    "FINN-ÖBÖL",
    "KALIFORNIAI-ÖBÖL",
    "ADENI-ÖBÖL",

    "MARIANA-ÁROK",
    "ALEUT-SZIGETEK",
    "ANTILLÁK",
    "KARIB-TENGER",
    "ARAB-TENGER",
    "JAPÁN-TENGER",
    "BERING-TENGER",
    "DÉL-KÍNAI-TENGER",
    "KORALL-TENGER",
    "TASMAN-TENGER",

    "ANTARKTISZ",
    "ÉSZAKI-SARK",
    "DÉLI-SARK",
    "EGYENLÍTŐ",
    "RÁKTÉRÍTŐ",
    "BAKTÉRÍTŐ",
    "ÉSZAKI-SARKKÖR",
    "DÉLI-SARKKÖR",
    "KEZDŐ HOSSZÚSÁGI KÖR",
    "DÁTUMVÁLASZTÓ VONAL",

    "ALFÖLD",
    "KISALFÖLD",
    "DUNÁNTÚLI-KÖZÉPHEGYSÉG",
    "ÉSZAKI-KÖZÉPHEGYSÉG",
    "BALATON",
    "VELENCEI-TÓ",
    "FERTŐ-TÓ",
    "DUNA-KANYAR",
    "HORTOBÁGY",
    "KISKUNSÁG"

];

module.exports = FOLDRAJZ;
	