const HASZNALATI_TARGY = [

    "KONYHASZEKRÉNY",
    "MOSÓGÉP",
    "PORSZÍVÓ",
    "KÁVÉFŐZŐ",
    "HŰTŐSZEKRÉNY",
    "VÍZFORRALÓ",
    "HAJSZÁRÍTÓ",
    "FOGKEFE",
    "ESERNYŐ",
    "TÁVIRÁNYÍTÓ",

    "MIKROHULLÁMÚ SÜTŐ",
    "KENYÉRPIRÍTÓ",
    "BOTMIXER",
    "TURMIXGÉP",
    "KONYHAI ROBOTGÉP",
    "GOFRISÜTŐ",
    "MELEGSZENDVICSSÜTŐ",
    "RIZSFŐZŐ",
    "LASSÚFŐZŐ",
    "OLAJMENTES SÜTŐ",

    "VILLANYTŰZHELY",
    "GÁZTŰZHELY",
    "SÜTŐ",
    "FŐZŐLAP",
    "PÁRAELSZÍVÓ",
    "MOSOGATÓGÉP",
    "MOSOGATÓTÁLCA",
    "CSEPEGTETŐTÁLCA",
    "VÁGÓDESZKA",
    "KONYHAKÉS",

    "KENYÉRVÁGÓ KÉS",
    "SAJTVÁGÓ",
    "HÁMOZÓ",
    "KONZERVNYITÓ",
    "DUGÓHÚZÓ",
    "ÜVEGNYITÓ",
    "DIÓTÖRŐ",
    "FOKHAGYMAPRÉS",
    "KRUMPLINYOMÓ",
    "HÚSKLOPFOLÓ",

    "RESZELŐ",
    "SZŰRŐKANÁL",
    "MERŐKANÁL",
    "FŐZŐKANÁL",
    "FALAPÁT",
    "HABVERŐ",
    "KONYHAI FOGÓ",
    "TÉSZTASZŰRŐ",
    "SZITA",
    "TÖLCSÉR",

    "MÉRŐPOHÁR",
    "MÉRŐKANÁL",
    "KONYHAI MÉRLEG",
    "HÚSDARÁLÓ",
    "TÉSZTAGÉP",
    "CITRUSPRÉS",
    "GYÜMÖLCSCENTRIFUGA",
    "JÉGKOCKATARTÓ",
    "TOJÁSTARTÓ",
    "FŰSZERTARTÓ",

    "CUKORTARTÓ",
    "SÓTARTÓ",
    "BORSŐRLŐ",
    "VAJTARTÓ",
    "KENYÉRTARTÓ",
    "SZALVÉTATARTÓ",
    "PAPÍRTÖRLŐ TARTÓ",
    "EDÉNYALÁTÉT",
    "POHÁRALÁTÉT",
    "LÁBAS",

    "FAZÉK",
    "SERPENYŐ",
    "WOK",
    "TEPSI",
    "SÜTŐFORMA",
    "TORTAFORMA",
    "MUFFINFORMA",
    "JÉNAI TÁL",
    "KEVERŐTÁL",
    "SALÁTÁSTÁL",

    "TÁNYÉR",
    "MÉLYTÁNYÉR",
    "KISTÁNYÉR",
    "BÖGRE",
    "CSÉSZE",
    "POHÁR",
    "BOROSPOHÁR",
    "PEZSGŐSPOHÁR",
    "KORSÓ",
    "KANÁL",

    "TEÁSKANÁL",
    "VILLA",
    "EVŐKÉS",
    "EVŐPÁLCIKA",
    "TÁLCA",
    "KANCÓ",
    "TERMOSZ",
    "KULACS",
    "UZSONNÁS DOBOZ",
    "ÉTELHORDÓ",
    "HŰTŐTÁSKA",
    "FRISSENTARTÓ DOBOZ",
    "BEFŐTTESÜVEG",
    "KONYHAI IDŐZÍTŐ",
    "KÖTÉNY",
    "EDÉNYFOGÓ KESZTYŰ",
    "KONYHARUHA",
    "MOSOGATÓKEFE",
    "MOSOGATÓSZIVACS",
    "MOSOGATÓSZER ADAGOLÓ",

    "SZEMETESKUKA",
    "SZELEKTÍV HULLADÉKGYŰJTŐ",
    "SEPRŰ",
    "SZEMETESLAPÁT",
    "FELMOSÓ",
    "FELMOSÓVÖDÖR",
    "PORTÖRLŐ",
    "ABLAKLEHÚZÓ",
    "TAKARÍTÓKEFE",
    "WC KEFE",

    "GUMIKESZTYŰ",
    "RUHASZÁRÍTÓ ÁLLVÁNY",
    "VASALÓ",
    "VASALÓDESZKA",
    "RUHAGŐZÖLŐ",
    "VARRÓGÉP",
    "VARRÓTŰ",
    "CÉRNAORSÓ",
    "OLLÓ",
    "BIZTOSÍTÓTŰ",

    "GYŰSZŰ",
    "MÉRŐSZALAG",
    "RUHAKEFE",
    "SZÖSZHENGER",
    "VÁLLFA",
    "RUHACSIPESZ",
    "SZENNYESTARTÓ",
    "RUHÁSKOSÁR",
    "ÁGY",
    "MATRAC",

    "PÁRNA",
    "TAKARÓ",
    "PAPLAN",
    "LEPEDŐ",
    "ÁGYTAKARÓ",
    "PÁRNAHUZAT",
    "PAPLANKHUZAT",
    "ÉJJELISZEKRÉNY",
    "RUHÁSSZEKRÉNY",
    "KOMÓD",

    "FIÓKOS SZEKRÉNY",
    "KÖNYVESPOLC",
    "FALIPOLC",
    "ÍRÓASZTAL",
    "SZÁMÍTÓGÉPASZTAL",
    "ÉTKEZŐASZTAL",
    "DOHÁNYZÓASZTAL",
    "SZÉK",
    "FOTEL",
    "KANAPÉ",

    "ÜLŐKE",
    "SÁMLI",
    "PAD",
    "BABZSÁKFOTEL",
    "CIPŐSSZEKRÉNY",
    "FOGAS",
    "KABÁTÁLLVÁNY",
    "TÜKÖR",
    "FALIÓRA",
    "ÉBRESZTŐÓRA",

    "ASZTALI LÁMPA",
    "ÁLLÓLÁMPA",
    "ÉJJELI LÁMPA",
    "MENNYEZETI LÁMPA",
    "ZSEBLÁMPA",
    "FEJLÁMPA",
    "GYERTYATARTÓ",
    "FÜGGÖNY",
    "SÖTÉTÍTŐFÜGGÖNY",
    "RELUXA",

    "ROLÓ",
    "SZŐNYEG",
    "LÁBTÖRLŐ",
    "DÍSZPÁRNA",
    "VÁZA",
    "KÉPKERET",
    "FÉNYKÉPALBUM",
    "TÁROLÓDOBOZ",
    "TÁROLÓKOSÁR",
    "IRATTARTÓ DOBOZ",

    "KULCSTARTÓ SZEKRÉNY",
    "PÉNZKAZETTA",
    "SZERSZÁMOSLÁDA",
    "BŐRÖND",
    "UTAZÓTÁSKA",
    "HÁTIZSÁK",
    "OLDALTÁSKA",
    "KÉZITÁSKA",
    "PÉNZTÁRCA",
    "IRATTÁRCA",
	"KULCSTARTÓ",
    "KÁRTYATARTÓ",
    "SZEMÜVEGTOK",
    "MOBILTOK",
    "LAPTOPTÁSKA",
    "LAPTOPHÁTIZSÁK",
    "ÖVTÁSKA",
    "SZAPPANTARTÓ",
    "SZAPPANADAGOLÓ",
    "TÖRÖLKÖZŐTARTÓ",

    "TÖRÖLKÖZŐ",
    "FÜRDŐLEPEDŐ",
    "KÖNTÖS",
    "FÜRDŐSZŐNYEG",
    "ZUHANYFÜGGÖNY",
    "ZUHANYRÓZSA",
    "ZUHANYCSŐ",
    "KÁDPARAVÁN",
    "KÖRÖMCSIPESZ",
    "KÖRÖMRESZELŐ",

    "CSIPESZ",
    "BOROTVA",
    "VILLANYBOROTVA",
    "HAJKEFE",
    "FÉSŰ",
    "HAJCSAVARÓ",
    "HAJVÁGÓGÉP",
    "SZAKÁLLVÁGÓ",
    "SMINKTÜKÖR",
    "VATTATARTÓ",

    "PAPÍRZSEBKENDŐ TARTÓ",
    "WC PAPÍR TARTÓ",
    "VÉRNYOMÁSMÉRŐ",
    "LÁZMÉRŐ",
    "SZEMÉLYMÉRLEG",
    "GYÓGYSZERADAGOLÓ",
    "ELSŐSEGÉLYDOBOZ",
    "JÁRÓBOT",
    "MANKÓ",
    "JÁRÓKERET",

    "KEREKESSZÉK",
    "ÍRÓGÉP",
    "SZÁMÍTÓGÉP",
    "LAPTOP",
    "TABLET",
    "OKOSTELEFON",
    "VEZETÉKES TELEFON",
    "MONITOR",
    "BILLENTYŰZET",
    "SZÁMÍTÓGÉPES EGÉR",

    "EGÉRPAD",
    "NYOMTATÓ",
    "SZKENNER",
    "FÉNYMÁSOLÓ",
    "IRATMEGSEMMISÍTŐ",
    "LAMINÁLÓGÉP",
    "CÍMKENYOMTATÓ",
    "PROJEKTOR",
    "VETÍTŐVÁSZON",
    "WEBKAMERA",

    "MIKROFON",
    "FEJHALLGATÓ",
    "FÜLHALLGATÓ",
    "HANGSZÓRÓ",
    "BLUETOOTH HANGSZÓRÓ",
    "RÁDIÓ",
    "HIFI TORONY",
    "LEMEZJÁTSZÓ",
    "CD LEJÁTSZÓ",
    "DVD LEJÁTSZÓ",

    "MÉDIALEJÁTSZÓ",
    "TELEVÍZIÓ",
    "JÁTÉKKONZOL",
    "JÁTÉKVEZÉRLŐ",
    "JOYSTICK",
    "MEMÓRIAKÁRTYA",
    "PENDRIVE",
    "KÜLSŐ MEREVLEMEZ",
    "USB ELOSZTÓ",
    "KÁRTYAOLVASÓ",

    "TELEFONTÖLTŐ",
    "LAPTOPTÖLTŐ",
    "POWERBANK",
    "HOSSZABBÍTÓ",
    "ELOSZTÓ",
    "HÁLÓZATI ADAPTER",
    "USB KÁBEL",
    "HDMI KÁBEL",
    "HÁLÓZATI KÁBEL",
    "ANTENNAKÁBEL",

    "ROUTER",
    "MODEM",
    "WIFI JELERŐSÍTŐ",
    "OKOSKONNEKTOR",
    "OKOSIZZÓ",
    "DIGITÁLIS ÓRA",
    "SZÁMOLÓGÉP",
    "DIKTAFON",
    "FÉNYKÉPEZŐGÉP",
    "VIDEOKAMERA",
	"FÉNYKÉPEZŐGÉP ÁLLVÁNY",
    "SZELFIBOT",
    "TÁVCSŐ",
    "NAGYÍTÓ",
    "IRÁNYTŰ",
    "GPS KÉSZÜLÉK",
    "LÉZERES TÁVOLSÁGMÉRŐ",
    "DIGITÁLIS HŐMÉRŐ",
    "PÁRATARTALOM MÉRŐ",
    "IDŐJÁRÁS ÁLLOMÁS",

    "GOLYÓSTOLL",
    "TÖLTŐTOLL",
    "CERUZA",
    "ROTRING",
    "SZÖVEGKIEMELŐ",
    "FILCTOLL",
    "KRÉTA",
    "RADÍR",
    "HEGYEZŐ",
    "VONALZÓ",

    "SZÖGMÉRŐ",
    "KÖRZŐ",
    "JEGYZETFÜZET",
    "FÜZET",
    "NAPLÓ",
    "HATÁRIDŐNAPLÓ",
    "MAPPATARTÓ",
    "GYŰRŰS MAPPA",
    "DOSSZIÉ",
    "IRATKAPOCS",

    "GÉMKAPOCS",
    "TŰZŐGÉP",
    "KAPOCSKISZEDŐ",
    "LYUKASZTÓ",
    "RAGASZTÓSTIFT",
    "RAGASZTÓSZALAG",
    "RAGASZTÓSZALAG ADAGOLÓ",
    "BORÍTÉK",
    "LEVÉLPAPÍR",
    "BÉLYEGZŐ",

    "BÉLYEGZŐPÁRNA",
    "NÉVKÁRTYATARTÓ",
    "ASZTALI RENDEZŐ",
    "CERUZATARTÓ",
    "PAPÍRKOSÁR",
    "VÁGÓALÁTÉT",
    "PAPÍRVÁGÓ",
    "SPIRÁLOZÓGÉP",
    "TÁBLATÖRLŐ",
    "RAJZTÁBLA",

    "KALAPÁCS",
    "GUMIKALAPÁCS",
    "CSAVARHÚZÓ",
    "CSILLAGCSAVARHÚZÓ",
    "LAPOSCSAVARHÚZÓ",
    "KOMBINÁLT FOGÓ",
    "CSÍPŐFOGÓ",
    "VÍZPUMPAFOGÓ",
    "FRANCIKULCS",
    "VILLÁSKULCS",

    "CSŐKULCS",
    "DUGÓKULCS",
    "IMBUSZKULCS",
    "RACSNISKULCS",
    "KÉZIFŰRÉSZ",
    "LOMBFŰRÉSZ",
    "FÉMFŰRÉSZ",
    "FÚRÓGÉP",
    "AKKUS CSAVAROZÓ",
    "SAROKCSISZOLÓ",

    "CSISZOLÓGÉP",
    "HŐLÉGFÚVÓ",
    "RAGASZTÓPISZTOLY",
    "FORRASZTÓPÁKA",
    "MÉRŐLÉC",
    "VÍZMÉRTÉK",
    "COLSTOK",
    "TOLÓMÉRŐ",
    "SATU",
    "MUNKAPAD",

    "LÉTRA",
    "LÉPCSŐS LÉTRA",
    "TALICSKA",
    "ÁSÓ",
    "KAPA",
    "GEREBLYE",
    "KERTI VILLA",
    "METSZŐOLLÓ",
    "SÖVÉNYVÁGÓ",
    "FŰNYÍRÓ",

    "FŰKASZA",
    "LOMBFÚVÓ",
    "KERTI TÖMLŐ",
    "LOCSOLÓKANNA",
    "SZÓRÓFEJ",
    "KERTI PERMETEZŐ",
    "KERTI KESZTYŰ",
    "VIRÁGCSERÉP",
    "VIRÁGLÁDA",
    "PALÁNTÁZÓLAPÁT",
	"KERTI TÉRDEPLŐ",
    "KOMPOSZTÁLÓ",
    "KERTI SZÉK",
    "KERTI ASZTAL",
    "NAPOZÓÁGY",
    "NAPERNYŐ",
    "KERTI PAD",
    "KERTI HINTA",
    "FÜGGŐÁGY",
    "MADÁRETETŐ",

    "KERÉKPÁR",
    "ROLLER",
    "GÖRDESZKA",
    "BUKÓSISAK",
    "KERÉKPÁRLÁMPA",
    "KERÉKPÁRCSENGŐ",
    "KERÉKPÁRPUMPA",
    "BICIKLIZÁR",
    "KULACSTARTÓ",
    "KERÉKPÁRTÁSKA",

    "AUTÓKULCS",
    "BIZTONSÁGI ÖV",
    "AUTÓS TELEFONTARTÓ",
    "AUTÓS TÖLTŐ",
    "JÉGKAPARÓ",
    "ABLAKMOSÓ KEFE",
    "ELAKADÁSJELZŐ HÁROMSZÖG",
    "LÁTHATÓSÁGI MELLÉNY",
    "INDÍTÓKÁBEL",
    "KERÉKKULCS",

    "AUTÓEMELŐ",
    "PÓTKERÉK",
    "LÉGNYOMÁSMÉRŐ",
    "AUTÓPORSZÍVÓ",
    "ÜLÉSHUZAT",
    "KORMÁNYVÉDŐ",
    "CSOMAGTÉRHÁLÓ",
    "TETŐCSOMAGTARTÓ",
    "GYEREKÜLÉS",
    "AUTÓS NAPSZELLENZŐ",

    "SÁTOR",
    "HÁLÓZSÁK",
    "POLIFOAM",
    "KEMPINGSZÉK",
    "KEMPINGASZTAL",
    "KEMPINGFŐZŐ",
    "TÚRABOT",
    "TÚRAHÁTIZSÁK",
    "VÍZSZŰRŐ PALACK",
    "SZÚNYOGRIASZTÓ",

    "PIKNIKKOSÁR",
    "PIKNIKPLÉD",
    "HORGÁSZBOT",
    "HORGÁSZORSÓ",
    "MERÍTŐHÁLÓ",
    "HALTARTÓ SZÁK",
    "HORGÁSZLÁDA",
    "CSALITARTÓ DOBOZ",
    "SPORTTÁSKA",
    "TORNAZSÁK",

    "FUTBALLLABDA",
    "KOSÁRLABDA",
    "RÖPLABDA",
    "TENISZÜTŐ",
    "TOLLASÜTŐ",
    "PINGPONGÜTŐ",
    "UGRÓKÖTÉL",
    "JÓGAMATRAC",
    "KÉZISÚLYZÓ",
    "STOPPERÓRA",

    "TÁRSASJÁTÉK",
    "KÁRTYAPAKLI",
    "SAKKTÁBLA",
    "SAKKÓRA",
    "DOMINÓKÉSZLET",
    "KIRAKÓJÁTÉK",
    "ÉPÍTŐKOCKA",
    "JÁTÉKAUTÓ",
    "PLÜSSJÁTÉK",
    "JÁTÉKBABA",

    "VARRÓDOBOZ",
    "ÉKSZERDOBOZ",
    "SZEMÜVEG",
    "NAPSZEMÜVEG",
    "KARPERECÓRA",
    "ÉKSZERTARTÓ",
    "CIPŐKANÁL",
    "CIPŐKEFE",
    "CIPŐFŰZŐ",
    "ESŐKABÁT",

    "BEVÁSÁRLÓKOSÁR",
    "BEVÁSÁRLÓTÁSKA",
    "KEREKES BEVÁSÁRLÓTÁSKA",
    "AJTÓKITÁMASZTÓ",
    "AJTÓCSENGŐ",
    "LEVÉLSZEKRÉNY",
    "LAKAT",
    "KULCS",
    "POROLTÓ KÉSZÜLÉK",
    "FÜSTÉRZÉKELŐ"

];

module.exports = HASZNALATI_TARGY;