const NOVENY = [

    "RÓZSA",
    "TULIPÁN",
    "NÁRCISZ",
    "JÁCINT",
    "IBOLYA",
    "ÁRVÁCSKA",
    "PETÚNIA",
    "MUSKÁTLI",
    "BEGÓNIA",
    "DÁLIA",

    "KRIZANTÉM",
    "GERBERA",
    "SZEGFŰ",
    "LEVENDULA",
    "LILIOM",
    "ÍRISZ",
    "KARDVIRÁG",
    "BAZSARÓZSA",
    "HORTENZIA",
    "MAGNÓLIA",

    "NAPRAFORGÓ",
    "PIPACS",
    "BÚZAVIRÁG",
    "GYÖNGYVIRÁG",
    "HÓVIRÁG",
    "KANKALIN",
    "NEFELEJCS",
    "MARGARÉTA",
    "KAMILLA",
    "KÖRÖMVIRÁG",

    "ORCHIDEA",
    "CIKLÁMEN",
    "AMARILLISZ",
    "AZÁLEA",
    "RODODENDRON",
    "LEANDER",
    "HIBISZKUSZ",
    "JÁZMIN",
    "ORGONA",
    "ARANYESŐ",

    "AKÁC",
    "TÖLGY",
    "BÜKK",
    "GYERTYÁN",
    "JUHAR",
    "KŐRIS",
    "SZIL",
    "NYÁRFA",
    "NYÍRFA",
    "FŰZFA",

    "HÁRSFA",
    "GESZTENYEFA",
    "PLATÁN",
    "ÉGERFA",
    "CÉDRUS",
    "CIPRUS",
    "FENYŐ",
    "LUCFENYŐ",
    "EZÜSTFENYŐ",
    "VÖRÖSFENYŐ",

    "ERDEIFENYŐ",
    "FEKETEFENYŐ",
    "JEGENYEFENYŐ",
    "TUJA",
    "BORÓKA",
    "TISZAFA",
    "MAMUTFENYŐ",
    "OLAJFA",
    "PÁLMA",
    "EUKALIPTUSZ",

    "ALMAFA",
    "KÖRTEFA",
    "CSERESZNYEFA",
    "MEGGYFA",
    "SZILVAFA",
    "ŐSZIBARACKFA",
    "KAJSZIBARACKFA",
    "BIRSALMAFA",
    "DIÓFA",
    "MOGYORÓBOKOR",

    "MANDULAFA",
    "FÜGEFA",
    "CITROMFA",
    "NARANCSFA",
    "MANDARINFA",
    "GRÁNÁTALMAFA",
    "DATOLYAPÁLMA",
    "BANÁNNÖVÉNY",
    "KÓKUSZPÁLMA",
    "AVOKÁDÓFA",

    "BAZSALIKOM",
    "ROZMARING",
    "KAKUKKFŰ",
    "OREGÁNÓ",
    "MENTA",
    "CITROMFŰ",
    "ZSÁLYA",
    "PETREZSELYEM",
    "KAPOR",
    "GYÖNGYHAGYMA",
	    "SÁRGARÉPA",
    "PETREZSELYEMGYÖKÉR",
    "ZELLER",
    "PASZTINÁK",
    "CÉKLA",
    "RETEK",
    "TORMA",
    "BURGONYA",
    "ÉDESBURGONYA",
    "CSICSÓKA",

    "VÖRÖSHAGYMA",
    "FOKHAGYMA",
    "PÓRÉHAGYMA",
    "LILAHAGYMA",
    "METÉLŐHAGYMA",
    "FEJES KÁPOSZTA",
    "VÖRÖS KÁPOSZTA",
    "KELKÁPOSZTA",
    "KARALÁBÉ",
    "KARFIOL",

    "BROKKOLI",
    "KELBIMBÓ",
    "SPENÓT",
    "SÓSKA",
    "FEJES SALÁTA",
    "JÉGSALÁTA",
    "MADÁRSALÁTA",
    "RUKKOLA",
    "MÁNGOLD",
    "SPÁRGA",

    "PARADICSOM",
    "PAPRIKA",
    "UBORKA",
    "CUKKINI",
    "PADLIZSÁN",
    "SÜTŐTÖK",
    "SPÁRGATÖK",
    "PATISSZON",
    "GÖRÖGDINNYE",
    "SÁRGADINNYE",

    "ZÖLDBORSÓ",
    "ZÖLDBAB",
    "SZÁRAZBAB",
    "LÓBAB",
    "SZÓJABAB",
    "CSICSERIBORSÓ",
    "LENCSE",
    "FÖLDIMOGYORÓ",
    "KUKORICA",
    "POPCORNKUKORICA",

    "BÚZA",
    "ÁRPA",
    "ROZS",
    "ZAB",
    "RIZS",
    "KÖLES",
    "HAJDINA",
    "CIROK",
    "TÖNKÖLYBÚZA",
    "DURUMBÚZA",

    "REPCE",
    "LEN",
    "KENDER",
    "MÁK",
    "SZEZÁM",
    "GYAPOT",
    "CUKORRÉPA",
    "CUKORNÁD",
    "DOHÁNY",
    "KOMLÓ",

    "CSALÁN",
    "PITYPANG",
    "ÚTIFŰ",
    "CICKAFARK",
    "ORBÁNCFŰ",
    "MACSKAGYÖKÉR",
    "BODZA",
    "CSIPKEBOGYÓ",
    "GALAGONYA",
    "FEKETE NADÁLYTŐ",

    "ÜRÖM",
    "IZSÓP",
    "TÁRKONY",
    "MAJORÁNNA",
    "KORIANDER",
    "ÁNIZS",
    "ÉDESKÖMÉNY",
    "KÖMÉNY",
    "LESTYÁN",
    "BABÉR",

    "NÁD",
    "GYÉKÉNY",
    "BÉKALENCSE",
    "TÜNDÉRRÓZSA",
    "VÍZITÖK",
    "ZSURLÓ",
    "PÁFRÁNY",
    "MOHA",
    "BOROSTYÁN",
    "FAGYÖNGY",
	    "KAKTUSZ",
    "FÜGEKAKTUSZ",
    "AGÁVÉ",
    "ALOE VERA",
    "KÖVIRÓZSA",
    "POZSGAFA",
    "ANYÓSNYELV",
    "SZOBAPÁFRÁNY",
    "SZOBABOROSTYÁN",
    "FILODENDRON",

    "MONSTERA",
    "FIKUSZ",
    "KROTON",
    "DIFENBACHIA",
    "DRACÉNA",
    "JUKKA",
    "VITORLAVIRÁG",
    "FLAMINGÓVIRÁG",
    "BROMÉLIA",
    "KARÁCSONYI KAKTUSZ",

    "MIKULÁSVIRÁG",
    "AFRIKAI IBOLYA",
    "VIASZVIRÁG",
    "PLETYKA",
    "SZOBACIKLÁMEN",
    "KÖNNYEZŐPÁLMA",
    "LEGYEZŐPÁLMA",
    "AREKAPÁLMA",
    "KENTIAPÁLMA",
    "BAMBUSZ",

    "BABÉRMEGGY",
    "BUXUS",
    "FAGYAL",
    "TŰZTÖVIS",
    "MADÁRBIRS",
    "SOM",
    "KÖKÉNY",
    "BORBOLYA",
    "HÓLYAGVESSZŐ",
    "JEZSÁMEN",

    "GYÖNGYVESSZŐ",
    "ARANYVESSZŐ",
    "MÁLYVACSERJE",
    "TAMARISKA",
    "LONC",
    "ISZALAG",
    "VADSZŐLŐ",
    "KOMLÓGYERTYÁN",
    "ECETFA",
    "CSÁSZÁRFA",

    "FEKETE RIBIZLI",
    "PIROS RIBIZLI",
    "FEHÉR RIBIZLI",
    "KÖSZMÉTE",
    "MÁLNA",
    "SZEDER",
    "ÁFONYA",
    "VÖRÖS ÁFONYA",
    "HOMOKTÖVIS",
    "ARÓNIA",

    "SZAMÓCA",
    "ERDEI SZAMÓCA",
    "SZŐLŐ",
    "KIVI",
    "MARACUJA",
    "ANANÁSZ",
    "MANGÓFA",
    "PAPAYAFA",
    "KAKAÓFA",
    "KÁVÉCSERJE",

    "TEACSERJE",
    "VANÍLIA",
    "FAHÉJFA",
    "SZEGFŰSZEGFA",
    "SZERECSENDIÓFA",
    "GYÖMBÉR",
    "KURKUMA",
    "KARDAMOM",
    "BORSNÖVÉNY",
    "CHILIPAPRIKA",

    "HANGA",
    "HARANGVIRÁG",
    "BOGLÁRKA",
    "SZARKALÁB",
    "GYŰSZŰVIRÁG",
    "OROSZLÁNSZÁJ",
    "BÁRSONYVIRÁG",
    "PORCSINRÓZSA",
    "DÍSZMÁK",
    "DÍSZNAPRAFORGÓ",

    "KOSBOR",
    "KOCKÁSLILIOM",
    "TAVASZI HÉRICS",
    "LEÁNYKÖKÖRCSIN",
    "ERDEI SZELLŐRÓZSA",
    "TŐZIKE",
    "VADÁRVÁCSKA",
    "MEZEI ZSÁLYA",
    "BÍBORHERE",
    "LUCERNA"

];

module.exports = NOVENY;