const SPORT = [

    "LABDARÚGÁS",
    "KÉZILABDA",
    "KOSÁRLABDA",
    "RÖPLABDA",
    "VÍZILABDA",
    "TENISZ",
    "ASZTALITENISZ",
    "TOLLASLABDA",
    "FALLABDA",
    "STRANDRÖPLABDA",

    "ÚSZÁS",
    "MŰÚSZÁS",
    "MŰUGRÁS",
    "VITORLÁZÁS",
    "KAJAKOZÁS",
    "KENUZÁS",
    "EVEZÉS",
    "SZÖRFÖZÉS",
    "VÍZISÍ",
    "RAFTING",

    "FUTÁS",
    "MARATONFUTÁS",
    "SPRINTFUTÁS",
    "GÁTFUTÁS",
    "VÁLTÓFUTÁS",
    "TÁVOLUGRÁS",
    "MAGASUGRÁS",
    "RÚDUGRÁS",
    "HÁRMASUGRÁS",
    "GERELYHAJÍTÁS",

    "DISZKOSZVETÉS",
    "KALAPÁCSVETÉS",
    "SÚLYLÖKÉS",
    "GYALOGLÁS",
    "TÍZPRÓBA",
    "HÉTPRÓBA",
    "TRIATLON",
    "ÖTTUSA",
    "TORNA",
    "RITMIKUS GIMNASZTIKA",

    "ÖKÖLVÍVÁS",
    "BIRKÓZÁS",
    "CSELGÁNCS",
    "KARATE",
    "TEKVANDÓ",
    "KICK-BOX",
    "VÍVÁS",
    "SZUMÓ",
    "KENDO",
    "BRAZIL JIU-JITSU",

    "KERÉKPÁROZÁS",
    "ORSZÁGÚTI KERÉKPÁROZÁS",
    "HEGYIKERÉKPÁROZÁS",
    "PÁLYAKERÉKPÁROZÁS",
    "BMX",
    "GÖRDESZKÁZÁS",
    "GÖRKORCSOLYÁZÁS",
    "SPORTMÁSZÁS",
    "SZIKLAMÁSZÁS",
    "TÁJFUTÁS",

    "SÍELÉS",
    "SÍFUTÁS",
    "SÍUGRÁS",
    "MŰKORCSOLYA",
    "GYORSKORCSOLYA",
    "JÉGKORONG",
    "CURLING",
    "SZÁNKÓZÁS",
    "BOB",
    "SNOWBOARD",

    "FORMA–1",
    "RALI",
    "MOTOKROSSZ",
    "GYORSASÁGI MOTOROZÁS",
    "GOKART",
    "LOVAGLÁS",
    "DÍJUGRATÁS",
    "DÍJLOVAGLÁS",
    "ÜGETŐVERSENY",
    "GALOPPVERSENY",

    "GOLF",
    "BASEBALL",
    "SOFTBALL",
    "AMERIKAI FUTBALL",
    "RÖGBI",
    "KRIKETT",
    "DARTS",
    "BILIÁRD",
    "SNOOKER",
    "TEKE",

    "SAKK",
    "SPORTLÖVÉSZET",
    "ÍJÁSZAT",
    "KÖTÉLHÚZÁS",
    "ERŐEMELÉS",
    "SÚLYEMELÉS",
    "TESTÉPÍTÉS",
    "FITNESZ",
    "AEROBIK",
    "TRAMBULIN",
	    "ARANYÉREM",
    "EZÜSTÉREM",
    "BRONZÉREM",
    "OLIMPIAI BAJNOK",
    "VILÁGBAJNOK",
    "EURÓPA-BAJNOK",
    "VILÁGREKORD",
    "OLIMPIAI REKORD",
    "DOBOGÓS HELYEZÉS",
    "BAJNOKI CÍM",

    "OLIMPIAI JÁTÉKOK",
    "NYÁRI OLIMPIA",
    "TÉLI OLIMPIA",
    "PARALIMPIAI JÁTÉKOK",
    "VILÁGBAJNOKSÁG",
    "EURÓPA-BAJNOKSÁG",
    "SELEJTEZŐ",
    "ELŐDÖNTŐ",
    "NEGYEDDÖNTŐ",
    "DÖNTŐ",

    "BÜNTETŐRÚGÁS",
    "SZABADRÚGÁS",
    "SZÖGLETRÚGÁS",
    "BEDOBÁS",
    "LESHELYZET",
    "SÁRGA LAP",
    "PIROS LAP",
    "KAPURA LÖVÉS",
    "FEJES GÓL",
    "ÖNGÓL",

    "TIZENEGYESPÁRBAJ",
    "MESTERHÁRMAS",
    "HOSSZABBÍTÁS",
    "CSEREJÁTÉKOS",
    "KAPUS",
    "HÁTVÉD",
    "KÖZÉPPÁLYÁS",
    "CSATÁR",
    "JÁTÉKVEZETŐ",
    "PARTJELZŐ",

    "KOSÁRRA DOBÁS",
    "HÁROMPONTOS DOBÁS",
    "BÜNTETŐDOBÁS",
    "ZSÁKOLÁS",
    "LEPATTANÓ",
    "LABDAVEZETÉS",
    "KOSÁRPALÁNK",
    "KOSÁRGYŰRŰ",
    "KEZDŐDOBÁS",
    "IDŐKÉRÉS",

    "NYITÁS",
    "SZERVA",
    "ÁSZ",
    "RÖPTE",
    "TENYERES",
    "FONÁK",
    "TENISZHÁLÓ",
    "TENISZÜTŐ",
    "TENISZLABDA",
    "TIE-BREAK",

    "KÉZILABDABÜNTETŐ",
    "HÉTMÉTERES",
    "KAPUELŐTÉR",
    "KÉZILABDAKAPU",
    "INDÍTÁS",
    "SÁNCKOLÁS",
    "RÖPLABDAHÁLÓ",
    "LEÜTÉS",
    "FELADÁS",
    "NYITÁSFOGADÁS",

    "RAJTKŐ",
    "RAJTJEL",
    "CÉLVONAL",
    "ÚSZÓMEDENCE",
    "ÚSZÓSÁV",
    "GYORSÚSZÁS",
    "HÁTÚSZÁS",
    "MELLÚSZÁS",
    "PILLANGÓÚSZÁS",
    "VEGYESÚSZÁS",

    "KNOCKOUT",
    "TECHNIKAI KNOCKOUT",
    "BOKSZKESZTYŰ",
    "BOKSZRING",
    "MENET",
    "PONTOZÓBÍRÓ",
    "VÍVÓPÁST",
    "VÍVÓMASZK",
    "PÁRBAJTŐR",
    "KARDVÍVÁS",

    "RAJTRÁCS",
    "BOXUTCA",
    "KOCKÁS ZÁSZLÓ",
    "POLE-POZÍCIÓ",
    "KERÉKCSERE",
    "BIZTONSÁGI AUTÓ",
    "VERSENYPÁLYA",
    "CÉLEGYENES",
    "LEGYORSABB KÖR",
    "RAJT-CÉL GYŐZELEM",
	    "FUTBALL-LABDA",
    "KAPUSHÁLÓ",
    "SÍPCSONTVÉDŐ",
    "STOPLIS CIPŐ",
    "KAPUSKESZTYŰ",
    "CSAPATKAPITÁNY",
    "KAPITÁNYI KARSZALAG",
    "BAJNOKI TRÓFEA",
    "GÓLKIRÁLY",
    "GÓLPASSZ",

    "LABDABIRTOKLÁS",
    "KÖZÉPKEZDÉS",
    "KIRÚGÁS",
    "KAPUFA",
    "SORFAL",
    "TÁMADÁS",
    "VÉDEKEZÉS",
    "ELLENTÁMADÁS",
    "HAZAI PÁLYA",
    "IDEGENBELI MÉRKŐZÉS",

   
    "KOSÁRLABDA-PÁLYA",
    "DUPLA DUPLA",
    "TRIPLA DUPLA",
    "DOBÓMOZDULAT",
    "LABDASZERZÉS",
    "BLOKKOLÁS",
    "KOSÁRLABDA-CSAPAT",
    "TÁMADÓIDŐ",
    "HOSSZABBÍTÁSOS MÉRKŐZÉS",

    "TENISZPÁLYA",
    "SALAKPÁLYA",
    "FÜVES PÁLYA",
    "KEMÉNY PÁLYA",
    "ADOGATÁS",
    "FOGADÁS",
    "HÁLÓJÁTÉK",
    "MECCSLABDA",
    "JÁTSZMA",
    "GRAND SLAM",

    "ÚSZÓSAPKA",
    "ÚSZÓSZEMÜVEG",
    "VÁLTÓÚSZÁS",
    "FORDULÓ",
    "CÉLBA ÉRKEZÉS",
    "RAJTUGRÁS",
    "MEDENCEHOSSZ",
    "NYÍLTVÍZI ÚSZÁS",
    "VÍZILABDA-KAPU",
    "VÍZILABDA-LABDA",

    "FUTÓPÁLYA",
    "RAJTPISTOLY",
    "VÁLTÓBOT",
    "CÉLSZALAG",
    "MARATONI TÁV",
    "AKADÁLYFUTÁS",
    "MEZEI FUTÁS",
    "ATLÉTIKAI PÁLYA",
    "UGRÓGÖDÖR",
    "DOBÓKÖR",

    "SÍLÉC",
    "SÍBOT",
    "SÍUGRÓSÁNC",
    "SÍPÁLYA",
    "SÍFELVONÓ",
    "KORCSOLYAPÁLYA",
    "JÉGKORONGÜTŐ",
    "JÉGKORONGKORONG",
    "JÉGKORONGKAPU",
    "BÜNTETŐPAD",

    "VERSENYKERÉKPÁR",
    "KERÉKPÁROS SISAK",
    "HEGYI SZAKASZ",
    "MEZŐNYHAJRÁ",
    "IDŐFUTAM",
    "SÁRGA TRIKÓ",
    "KOCKAKÖVES SZAKASZ",
    "KERÉKPÁROS PELOTON",
    "CÉLFOTÓ",
    "SZÖKÉSBEN LÉVŐ VERSENYZŐ",

    "SAKKFIGURA",
    "SAKKTÁBLA",
    "SAKK-MATT",
    "SÁNCLÉPÉS",
    "GYALOG",
    "FUTÓ",
    "HUSZÁR",
    "BÁSTYA",
    "VEZÉR",
    "KIRÁLY",

    "SPORTCSARNOK",
    "LELÁTÓ",
    "EREDMÉNYJELZŐ",
    "GYŐZELMI SERLEG",
    "ÉREMÁTADÁS",
    "DOPPINGVIZSGÁLAT",
    "EDZŐTÁBOR",
    "BEMELEGÍTÉS",
    "LEVEZETÉS",
    "SPORTSZERŰSÉG",
    "WING CHUN",
    "ESKRIMA",
];

module.exports = SPORT;