const ZENE = [

    "ZONGORA",
    "HEGEDŰ",
    "BRÁCSA",
    "GORDONKA",
    "NAGYBŐGŐ",
    "HÁRFA",
    "GITÁR",
    "AKUSZTIKUS GITÁR",
    "ELEKTROMOS GITÁR",
    "BASSZUSGITÁR",

    "FUVOLA",
    "PIKKOLÓ",
    "KLARINÉT",
    "OBOA",
    "FAGOTT",
    "SZAXOFON",
    "TROMBITA",
    "HARSONA",
    "VADÁSZKÜRT",
    "TUBA",

    "DOBFELSZERELÉS",
    "ÜSTDOB",
    "TAMBURIN",
    "TRIANGULUM",
    "CINTÁNYÉR",
    "XYLOFON",
    "MARIMBA",
    "VIBRAFON",
    "KASZTANYETTA",
    "CSÖRGŐDOB",

    "HARMONIKA",
    "TANGÓHARMONIKA",
    "ORGONA",
    "SZINTETIZÁTOR",
    "CSEMBALÓ",
    "CITERA",
    "TÁROGATÓ",
    "FURULYA",
    "DUDA",
    "KÖCSÖGDUDA",

    "NÉPDAL",
    "NÉPZENE",
    "KOMOLYZENE",
    "KÖNNYŰZENE",
    "POPZENE",
    "ROCKZENE",
    "HARD ROCK",
    "HEAVY METAL",
    "PUNK ROCK",
    "ALTERNATÍV ROCK",

    "JAZZ",
    "BLUES",
    "SOUL",
    "FUNK",
    "DISZKÓ",
    "REGGAE",
    "COUNTRY",
    "GOSPEL",
    "HIPHOP",
    "RAP",

    "TECHNO",
    "HOUSE",
    "TRANCE",
    "DANCE",
    "DUBSTEP",
    "DRUM AND BASS",
    "ELEKTRONIKUS ZENE",
    "FILMZENE",
    "MUSICAL",
    "OPERETT",

    "OPERA",
    "SZIMFÓNIA",
    "SZONÁTA",
    "KONCERT",
    "KAMARAZENE",
    "KÓRUSMŰ",
    "DAL",
    "BALLADA",
    "INDULÓ",
    "HIMNUSZ",

    "DALLAM",
    "RITMUS",
    "TEMPÓ",
    "HANGMAGASSÁG",
    "HANGERŐ",
    "HANGNEM",
    "AKKORD",
    "HARMÓNIA",
    "REFRÉN",
    "VERSSZAK",

    "KOTTA",
    "KULCS",
    "HANGJEGY",
    "SZÜNETJEL",
    "ÜTEM",
    "ÜTEMMUTATÓ",
    "KARMESTER",
    "ZENEKAR",
    "ÉNEKKAR",
    "SZÓLÓÉNEKES",
	    "ÉNEKES",
    "ÉNEKESNŐ",
    "ZENESZERZŐ",
    "DALSZERZŐ",
    "SZÖVEGÍRÓ",
    "ZENÉSZ",
    "ZONGORISTA",
    "HEGEDŰMŰVÉSZ",
    "GITÁROS",
    "DOBOS",

    "BASSZUSGITÁROS",
    "SZAXOFONOS",
    "TROMBITÁS",
    "HÁRFAMŰVÉSZ",
    "ORGONISTA",
    "KÓRUSVEZETŐ",
    "KONCERTMESTER",
    "KARMESTERI PÁLCA",
    "MIKROFON",
    "MIKROFONÁLLVÁNY",

    "HANGFAL",
    "ERŐSÍTŐ",
    "KEVERŐPULT",
    "FEJHALLGATÓ",
    "HANGSTÚDIÓ",
    "LEMEZSTÚDIÓ",
    "KONCERTTEREM",
    "SZÍNPAD",
    "ZENEKARI ÁROK",
    "PRÓBATEREM",

    "HANGLEMEZ",
    "BAKELITLEMEZ",
    "LEMEZJÁTSZÓ",
    "HANGKAZETTA",
    "MAGNÓSZALAG",
    "KOMPAKTLEMEZ",
    "ZENEI ALBUM",
    "KISLEMEZ",
    "VÁLOGATÁSLEMEZ",
    "KONCERTFELVÉTEL",

    "ZENEI FESZTIVÁL",
    "ÉLŐ KONCERT",
    "SZABADTÉRI KONCERT",
    "JÓTÉKONYSÁGI KONCERT",
    "VILÁGKÖRÜLI TURNÉ",
    "KONCERTTURNÉ",
    "RÁADÁS",
    "HANGPRÓBA",
    "FŐPRÓBA",
    "PREMIER",

    "DUETT",
    "TRIÓ",
    "KVARTETT",
    "KVINTETT",
    "VOKÁL",
    "HÁTTÉRVOKÁL",
    "A CAPPELLA",
    "KÁNON",
    "IMPROVIZÁCIÓ",
    "ZENEI ÁTDOLGOZÁS",

    "DALSZÖVEG",
    "KOTTATARTÓ",
    "KOTTAFÜZET",
    "KOTTAPAPÍR",
    "VIOLINKULCS",
    "BASSZUSKULCS",
    "KERESZT",
    "BÉ",
    "DÚR HANGNEM",
    "MOLL HANGNEM",

    "FÉLHANG",
    "EGÉSZ HANG",
    "OKTÁV",
    "HANGKÖZ",
    "HANGSOR",
    "SKÁLA",
    "DÚR SKÁLA",
    "MOLL SKÁLA",
    "PENTATON SKÁLA",
    "KROMATIKUS SKÁLA",

    "ALLEGRO",
    "ADAGIO",
    "ANDANTE",
    "PRESTO",
    "LARGO",
    "CRESCENDO",
    "DECRESCENDO",
    "FORTE",
    "PIANO",
    "LEGATO",

    "STACCATO",
    "VIBRATO",
    "GLISSANDO",
    "ARPEGGIO",
    "PIZZICATO",
    "SZOPRÁN",
    "ALT",
    "TENOR",
    "BARITON",
    "BASSZUS",
	    "AKKORDEON",
    "BANDONEON",
    "MANDOLIN",
    "UKULELE",
    "BENDZSÓ",
    "LANT",
    "BALALAJKA",
    "SZITÁR",
    "LÍRA",
    "KOTO",

    "PÁNSÍP",
    "OKARINA",
    "SZÁJHARMONIKA",
    "DOROMB",
    "TILINKÓ",
    "HAVASI KÜRT",
    "ALPHORN",
    "GONG",
    "HARANGJÁTÉK",
    "CSŐHARANG",

    "BONGÓ",
    "KONGA",
    "DJEMBE",
    "MARACAS",
    "GUIRO",
    "KOLOMP",
    "KEREPLŐ",
    "DOBVERŐ",
    "LÁBDOB",
    "PERGŐDOB",

    "RÉZFÚVÓS HANGSZER",
    "FAFÚVÓS HANGSZER",
    "VONÓS HANGSZER",
    "PENGETŐS HANGSZER",
    "ÜTŐHANGSZER",
    "BILLENTYŰS HANGSZER",
    "SZIMFONIKUS ZENEKAR",
    "FÚVÓSZENEKAR",
    "KAMARAZENEKAR",
    "CIGÁNYZENEKAR",

    "VONÓSNÉGYES",
    "FÚVÓSÖTÖS",
    "NAGYZENEKAR",
    "BIG BAND",
    "ROCKZENEKAR",
    "NÉPZENEKAR",
    "ZENEKARI PRÓBA",
    "KÓRUSPRÓBA",
    "KONCERTPROGRAM",
    "ZENEKARI PARTITÚRA",

    "KÓRUS",
    "VEGYESKAR",
    "FÉRFIKAR",
    "NŐIKAR",
    "GYERMEKKÓRUS",
    "KAMARAKÓRUS",
    "KÓRUSÉNEKLÉS",
    "SZÓLÓÉNEK",
    "TÖBBSZÓLAMÚ ÉNEKLÉS",
    "NÉPÉNEK",

    "HANGKÉPZÉS",
    "LÉGZÉSTECHNIKA",
    "HANGTERJEDELEM",
    "ÉNEKHANG",
    "MÉLY HANG",
    "MAGAS HANG",
    "TISZTA HANG",
    "HAMIS HANG",
    "HANGSZÍN",
    "HANGVILLA",

    "METRONÓM",
    "KOTTAVONAL",
    "KOTTAFEJ",
    "SZÁR",
    "GERENDA",
    "ELŐJEGYZÉS",
    "MÓDOSÍTÓJEL",
    "FELOLDÓJEL",
    "ISMÉTLŐJEL",
    "ZÁRÓVONAL",

    "BEVEZETŐ",
    "ELŐJÁTÉK",
    "KÖZJÁTÉK",
    "UTÓJÁTÉK",
    "FINÁLÉ",
    "NYITÁNY",
    "INTERMEZZO",
    "ETŰD",
    "RAPSZÓDIA",
    "FANTÁZIA",

    "KANTÁTA",
    "ORATÓRIUM",
    "REKVIEM",
    "MISÉTÉTEL",
    "KAMARAKONCERT",
    "ZONGORAVERSENY",
    "HEGEDŰVERSENY",
    "ZENÉS SZÍNHÁZ",
    "KONCERTJEGY",
    "LEMEZBORÍTÓ"

];

module.exports = ZENE;